- name: Install dependencies for setting up sources
  ansible.builtin.apt:
    name:
      - curl
      - gnupg2
      - lsb-release
    update_cache: true
  become: true

# sudo curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg
- name: Authorize ROS GPG key
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/ros/rosdistro/master/ros.key
    dest: /usr/share/keyrings/ros-archive-keyring.gpg
  become: true

- name: Save result of 'dpkg --print-architecture'
  ansible.builtin.command: dpkg --print-architecture
  register: deb_architecture

- name: Save result of 'source /etc/os-release && echo $UBUNTU_CODENAME'
  ansible.builtin.shell: bash -c 'source /etc/os-release && echo $UBUNTU_CODENAME'
  register: ubuntu_codename

# echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(source /etc/os-release && echo $UBUNTU_CODENAME) main" | sudo tee /etc/apt/sources.list.d/ros2.list > /dev/null
- name: Add ROS 2 apt repository to source list
  ansible.builtin.apt_repository:
    repo: deb [arch={{ deb_architecture.stdout }} signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu {{ ubuntu_codename.stdout }} main
    filename: ros2
    state: present
    update_cache: true
  become: true

- name: Install ros-{{ rosdistro }}-{{ installation_type }}
  ansible.builtin.apt:
    name: ros-{{ rosdistro }}-{{ installation_type }}
    state: latest
    update_cache: true
  become: true
